[package]
name = "voronoice"
version = "0.0.1"
authors = ["Andre Esteve <andreesteve@gmail.com>"]
edition = "2018"

[dependencies]
delaunator = "0.2.0"

[dev-dependencies]
criterion = "0.3.3"
rand = "0.8.1"

[[bench]]
name = "quick"
harness = false

[[bench]]
name = "large_input_benchmark"
harness = false

[[bench]]
name = "compare_with_deps"
harness = false