[package]
name = "voronoi"
version = "0.1.0"
authors = ["Andre Esteve <andreesteve@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.4.0"
delaunator = "0.2.0"
rand = "*"

[profile.dev.package."*"]
opt-level = 3