[package]
name = "voronoice"
version = "0.0.1"
authors = ["Andre Esteve <andreesteve@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.4.0"
delaunator = "0.2.0"
rand = "0.8.1"

[dev-dependencies]
criterion = "0.3.3"

[[bench]]
name = "my_benchmark"
harness = false

[[bench]]
name = "compare_with_deps"
harness = false

[profile.dev.package."*"]
opt-level = 3
